webui/translator/urls.py
from django.urls import path

from . import views

app_name="translator"
urlpatterns = [
    path("", views.FormWithFilesView.as_view(), name="index"),
    path("files/upload",views.FormWithFilesView.as_view(),name="translator_file"),
    path("files/uploadFileAndTranslate",views.uploadFileAndTranslate,name="uploadFileAndTranslate"),
]

webui/webui/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('translator.urls')),
    path('translator/', include('translator.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webui/translator/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Welcome(models.Model):
    id = models.BigAutoField(primary_key=True)
    welcome_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.welcome_text


class FileUploadNumberRecord(models.Model):
    id = models.BigAutoField(primary_key=True)
    login_user_id = models.BigIntegerField('login user id')
    file_type = models.IntegerField()
    file_upload_time = models.DateTimeField("file upload date time")

    def __str__(self):
        return f'FileType:{self.file_type},FileUploadTime:{self.file_upload_time}'

    def was_uploaded_recently(self):
        return self.file_upload_time >= timezone.now() - datetime.timedelta(days=7)


class FileSpeedLimitedConfiguration(models.Model):
    id = models.BigAutoField(primary_key=True)
    user_type = models.IntegerField(
        db_comment="user type 1: anonymous user,2:login user")
    limited_qps = models.IntegerField(
        db_comment="limited qps. 1qps for anonymous user,10 qps  for  login user ")

    def __str__(self):
        return f'UserType:{self.user_type},LimitedQPS:{self.limited_qps}'


class SiteUser(models.Model):
    id = models.BigAutoField(primary_key=True)
    user_serial_no = models.CharField(max_length=64)
    user_name = models.CharField(max_length=64)
    last_login_date_time = models.DateTimeField()
    allowed_qps = models.IntegerField(default=10)
    user_login_status = models.IntegerField(
        db_comment="1: login 2: don't login", default=2)

    def __str__(self):
        return self.user_name


class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField("date published")

    def __str__(self):
        return  self.question_text

    def was_published_recently(self):
        return  self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class FileUpload(models.Model):
    title=models.TextField();
    cover=models.ImageField(upload_to='images/')
    wait_translated_file=models.FileField(upload_to='files/')

    def __str__(self):
        return self.title

webui/translator/forms.py
from django import forms
from django.contrib.admin.widgets import AdminSplitDateTime
from django.forms import BaseFormSet, TextInput, formset_factory

from django_bootstrap5.widgets import RadioSelectButtonGroup

from .models import FileUpload


SUPPORT_LANGUAGE = (
    ("1", "简体中文"),
    ("2", "繁体中文"),
    ("3", "English"),
    ("4", "日本語"),
)
SUPPORT_LANGUAGE_DEFAULT = "1"


def getLanguage(code):
    for lang_code, lang_name in SUPPORT_LANGUAGE:
        if lang_code == code:
            return lang_name
    return "简体中文"


SUPPORT_FORMAT = (
    ("1", "PDF"),
    ("2", "Markdown"),
)


SUPPORT_FORMAT_DEFAULT = "1"


def getFormat(format):
    for format_code, format_name in SUPPORT_FORMAT:
        if format_code == format:
            return format_name
    return "pdf"


class FilesForm(forms.Form):
    pdfUpload = forms.FileField(
        widget=forms.ClearableFileInput, label="Please upload file(pdf):", required=True)
    fileLanguageList = forms.ChoiceField(
        choices=SUPPORT_LANGUAGE, label="Target Language:", required=True, initial=SUPPORT_LANGUAGE_DEFAULT)
    fileFormatList = forms.ChoiceField(
        choices=SUPPORT_FORMAT, label="Traget Format:", required=True, initial=SUPPORT_FORMAT_DEFAULT)
    use_required_attribute = True

webui/translator/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from .models import FileSpeedLimitedConfiguration, Question, Choice, FileUpload
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
from .forms import FilesForm
from django.contrib import messages
from django.core.files.storage import default_storage
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models.fields.files import FieldFile
from django.views.generic import FormView
from django.views.generic.base import TemplateView
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from .ai_translator.model import OpenAIModel
from .ai_translator.translator import PDFTranslator
from .ai_translator.utils import LOG
from .forms import getFormat, getLanguage
from django.views.decorators.csrf import csrf_exempt

import uuid
import random
import os
upload_dir = os.path.join(settings.MEDIA_ROOT, 'file')
if not os.path.exists(upload_dir):
    os.makedirs(upload_dir)


class LocalFileSystemStorage(FileSystemStorage):
    pass


fs = LocalFileSystemStorage(location=upload_dir)


# Create your views here.

class GetParametersMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["layout"] = self.request.GET.get("layout", None)
        context["size"] = self.request.GET.get("size", None)
        return context


class FormWithFilesView(GetParametersMixin, FormView):
    template_name = "translator/filetranslator.html"
    form_class = FilesForm
    success_url = "/files/download"

    def get_initial(self):
        return {}


@csrf_exempt
def uploadFileAndTranslate(request):
    if request.method == 'POST':
        # 待翻译的 PDF文件
        pdfFile = request.FILES['file']

        # 转换后的语言和格式
        fileLanguage = getLanguage(request.POST.get("fileLanguage"))
        fileFormat = getFormat(request.POST.get("fileFormat"))

        LOG.info(f'TargetLanguage:{fileLanguage},TargetFormat:{fileFormat}')

        # 生成本地缓存的文件名称，并且保存文件信息，方便后续读取翻译
        _, file_extension = os.path.splitext(pdfFile.name)
        fileSavePath = f'{uuid.uuid4().hex}{file_extension}'
        saved_file_path = os.path.join(upload_dir, fileSavePath)
        with open(saved_file_path, "wb+") as destination:
            for chunk in pdfFile.chunks():
                destination.write(chunk)


        #解析文件后缀
        fileSuffix=".pdf"
        if fileFormat.lower() =='pdf':
            fileSuffix='.pdf'
        elif fileFormat.lower()=='markdown':
            fileSuffix='.md'    

        # 输出保存后的文件路径
        LOG.info(
            f'pdf file cached to: {saved_file_path}.will be removed after be translated')
        LOG.info(f'Start to translator')
        output_file_path = saved_file_path.replace(".pdf", f'_translated{fileSuffix}')

        # 加在OpenAI模型
        model = OpenAIModel(model="gpt-3.5-turbo",
                            api_key=os.environ["OPENAI_API_KEY"])

        # 初始化翻译
        translator = PDFTranslator(model)

        # 调用翻译方法进行文件处理
        translator.translate_pdf(
            saved_file_path, output_file_path=output_file_path, file_format=fileFormat, target_language=fileLanguage)
        # read pdf file and translate to en_US
        # save local file and gen url to front
        # 构造前端使用的URL地址方便用户下载
        return JsonResponse({
            "success": True,
            "downloadUrl": f"{settings.MEDIA_URL}file/{fileSavePath.replace(file_extension,f'_translated{fileSuffix}')}",
            "fileName": fileSavePath.replace(file_extension, f'_translated{fileSuffix}')
        })
    return JsonResponse({"success": True})

webui/translator/templates/translator/filetranslator.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_messages %}
</head>

<body>

  {% block content %}

  <form id="uploadFileForm" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% bootstrap_form form layout=layout %}

    {% bootstrap_button button_type="submit" content="OK" %}
    {% bootstrap_button button_type="reset" content="Cancel" %}
  </form>

  {% endblock %}
  <!-- Modal -->
  <div class="modal fade" id="downloadFileModel" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Translate Completed</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <a id="downloadFile" href="" target="_blank"></a>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
  {% bootstrap_javascript %}
  <script>
    $(function () {
      var downloadFileModel = new bootstrap.Modal(document.getElementById('downloadFileModel'), {
      })
      $('#uploadFileForm').on('submit', function (event) {
        event.preventDefault();
        var formData = new FormData();
        formData.append('file', $("#id_pdfUpload").prop("files")[0])
        // formData.append('csrfmiddlewaretoken', $($("#uploadFileForm").children("input[name=csrfmiddlewaretoken]")[0]).val())
        formData.append('fileLanguage', $("#id_fileLanguageList").val())
        formData.append('fileFormat', $("#id_fileFormatList").val())
        $.ajax({
          url: '{% url "translator:uploadFileAndTranslate" %}',
          type: 'POST',
          data: formData,
          contentType: false,
          cache: false,
          processData: false,
          success: function (response) {
            if (response.success) {
              $("#downloadFile").attr('href', response.downloadUrl);
              $("#downloadFile").text(response.fileName);
              downloadFileModel.show();
            } else {

            }
          }
        });
      });
    })
  </script>
</body>

</html>